version: '2'

services:
  ota-server:
    build: .
    container_name: ota-server
    environment:
      - NODE_ENV=production
    ports:
      - 7000:7000
    links:
      - redis
      - mongodb
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis:alpine
    container_name: 'redis'
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod